name: main

on: push

jobs:
  build:
    name: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir _build
        cd _build
        cmake ..
    - name: build
      run: |
        cd _build
        cmake --build .
    - name: test
      run: |
        cd _build
        # -C Debug: chose "Debug" if multiple build configs available,
        # like in Visual Studio Solutions, -V: verbose output
        ctest -C Debug -V
